# Generated by Django 5.1 on 2024-08-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
                ('description', models.TextField(max_length=1000)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
